global_costmap:
  global_frame: odom
  rolling_window: true
  static_map: false

  plugins:
  - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}